import Footer from '@/components/layout/Footer';
import Nav from '@/components/layout/Nav';

import '@/styles/main.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
